name: auto_login_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  logger: ^2.0.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.2
  connectivity_plus: ^4.0.2
  flutter_secure_storage: ^9.0.0
  mockito: ^5.4.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  test: ^1.24.1

flutter:
  uses-material-design: true
  assets:
    - lib/src/core/config/dev.env
    - lib/src/core/config/prod.env